// ─── TAME TEXT POOLS ─────────────────────────────────────────────────────────
// Tüm metin havuzları burada tanımlanır.
// tame-narrative.ts tarafından import edilir.

import type { OwlPersonality, TameAction } from './tame-narrative';

export const INTRO_TEXTS: Record<OwlPersonality, string[]> = {
  aggressive: [
    'Baykuş seni görür görmez tüylerini kabarttı. Gözleri dar, nefesi hızlı. Bu bir uyarı.',
    'Dalın üzerinde öylece duruyor — ama kasları gergin, pençeleri kıvrık. Saldırmaya hazır.',
    'Seni fark etti. Başını öne eğdi, gagasını açtı. Sessizlik tehditten daha ağır.',
    'Kanatlarını yarı açtı. Büyük görünmek istiyor. Gözleri senden ayrılmıyor.',
    'Bir adım attın, o iki adım geri çekildi — ama kaçmadı. Savaşmayı tercih ediyor.',
    'Tüyleri diken diken. Sesi yok ama vücudu bağırıyor: "Yaklaşma."',
    'Seni tepeden tırnağa süzdü. Sonra gagasını tıklattı. Bu bir meydan okuma.',
    'Gözleri sarı, bakışları keskin. Seni zaten ölçtü, biçti. Karar vermedi henüz.',
    'Daldan dala atladı, seni takip ediyor. Kaçmıyor — izliyor. Fırsatını bekliyor.',
    'Aniden bir çığlık attı. Orman sustu. Sadece sen ve o kaldınız.',
    'Pençelerini dala geçirdi, sıkıştırdı. Hazır pozisyon. Bir hamle bekleniyor.',
    'Sana doğru döndü, kanatlarını açtı. Rüzgar yüzüne çarptı. Mesaj açık.',
    'Gözlerini kırpmadan seni izliyor. Sabırsız değil — emin olmayı bekliyor.',
    'Başını sağa sola çevirdi, sonra sana kilitledi. Artık sadece sen varsın.',
    'Bir tüy düştü. Rüzgar yoktu. Kasıtlıydı.',
  ],
  timid: [
    'Seni görünce hemen dala yapıştı. Küçük, titrek, gözleri kocaman açık.',
    'Kanatlarını vücuduna çekti. Görünmez olmaya çalışıyor. Ama sen gördün.',
    'Bir adım attın, o üç adım geri çekildi. Kaçmak istiyor ama bir şey onu tutuyor.',
    'Gözleri sürekli etrafı tarıyor. Tehlike mi var? Sadece sen varsın.',
    'Tüyleri hafifçe titredi. Rüzgar yoktu. Korkudan.',
    'Seni fark edince dondu. Nefes almıyor gibi. Bekliyor.',
    'Küçük bir ses çıkardı — yarım kalmış bir çığlık. Sonra sustu.',
    'Dalın arkasına geçmeye çalıştı. Ama dal çok ince. Hâlâ görünüyor.',
    'Başını içeri çekti, boyun yok gibi. Küçülmeye çalışıyor.',
    'Gözleri yaşlı gibi parlıyor. Yorgun mu, korkmuş mu — belli değil.',
    'Sana bakmıyor. Ama her hareketini hissediyor.',
    'Ayakları titriyor. Dal hafifçe sallanıyor. Fark etti mi bilmiyorsun.',
    'Bir yaprak düştü. Zıpladı. Sonra utanmış gibi durdu.',
    'Sesi yok. Hareketi yok. Sadece gözleri — büyük, derin, korkmuş.',
    'Kaçmak için hazırlandı ama kaçmadı. İçinde bir şey onu merak ettiriyor.',
  ],
  curious: [
    'Başını yana eğdi. Seni inceliyor — tehdit değil, merak.',
    'Sana doğru bir adım attı. Sonra durdu. Sonra bir adım daha.',
    'Gözleri parlıyor. Yeni bir şey gördü. Sen.',
    'Gagasını açıp kapattı. Bir şey söylemek istedi mi? Bilmiyorsun.',
    'Etrafında döndü, seni her açıdan inceledi. Bir nesne gibi.',
    'Tüylerini kabarttı — ama saldırgan değil. Daha büyük görünmek istiyor, daha iyi görmek için.',
    'Sana doğru uçtu, tam önünde durdu. Mesafe: iki adım. Gözleri meraklı.',
    'Başını öne uzattı, burnunu — gagasını — sana doğru yöneltti. Koku alıyor.',
    'Bir şey buldu yerde. Sonra sana baktı. Sonra tekrar yere. Karşılaştırıyor.',
    'Kanatlarını açtı, kapattı. Açtı, kapattı. Bir ritüel mi, sinyal mi?',
    'Seni taklit etti. Elini kaldırdın, o kanadını kaldırdı. Tesadüf mü?',
    'Gözlerini kırptı. Yavaşça. Güven işareti mi, yoksa tuzak mı?',
    'Sesin geldiği yöne döndü. Sonra sana döndü. Bağlantı kurdu.',
    'Daldan aşağı sarktı, baş aşağı seni inceledi. Alışılmadık bir bakış açısı.',
    'Küçük bir ses çıkardı. Soru gibi. Cevap bekliyordu.',
  ],
  greedy: [
    'Gözleri ellerine takıldı. Bir şey mi var? Yok. Hayal kırıklığı.',
    'Sana yaklaştı — ama seni değil, üzerindeki kokuyu arıyor.',
    'Etrafında döndü. Bir şey arıyor. Değerli bir şey.',
    'Gagasını açtı, kapattı. Açtı, kapattı. Bir şey bekliyor.',
    'Gözleri parlıyor — ama içten değil. Hesaplıyor.',
    'Sana yaklaştı, sonra geri çekildi. Fiyatı biçiyor.',
    'Bir şey düşürdün mü? Hemen oraya baktı. Hayır. Hayal kırıklığı.',
    'Seni inceliyor — ama seni değil, ne getirebileceğini.',
    'Kanatlarını açtı. Büyük görünmek istiyor. Pazarlık pozisyonu.',
    'Başını eğdi, sana baktı. Gözlerinde bir hesap var.',
    'Etraftaki her şeyi kontrol etti. Sonra sana döndü. Son seçenek.',
    'Bir ses çıkardı — talep gibi. Beklenti var.',
    'Pençelerini gösterdi. Sahip olduğu şeyleri sayıyor.',
    'Sana yaklaştı, durdu. Bir şey sunman gerekiyor.',
    'Gözleri sürekli hareket ediyor. Fırsat arıyor.',
  ],
  wise: [
    'Seni çoktan fark etmişti. Ama beklemesini biliyor.',
    'Gözleri derin, sakin. Seni ölçüyor — aceleyle değil, sabırla.',
    'Dalda öylece duruyor. Rüzgar esiyor, o kıpırdamıyor. Kök gibi.',
    'Başını hafifçe eğdi. Selamlama mı, uyarı mı — ikisi de olabilir.',
    'Seni izliyor ama gözlerini dikmiyor. Çevre farkındalığı tam.',
    'Bir süre sessiz kaldı. Sonra tek bir ses çıkardı. Anlam dolu.',
    'Kanatlarını açmadı. Tüylerini kabartmadı. Sadece bekledi.',
    'Gözleri sana değil, arkana bakıyor. Tehlike mi kontrol ediyor?',
    'Yavaşça döndü. Her hareketi kasıtlı, her bakış hesaplı.',
    'Seni test ediyor. Nasıl yaklaştığını, ne hissettirdiğini ölçüyor.',
    'Uzun süre baktı. Sonra gözlerini kapattı. Sonra açtı. Karar verdi.',
    'Etrafındaki her şeyi biliyor. Sen de dahilsin artık.',
    'Bir tüy düşürdü. Kasıtlı. Bir işaret mi?',
    'Sesi yok. Ama varlığı ağır. Ormanın kendisi gibi.',
    'Sana baktı, sonra ufka baktı. Sonra tekrar sana. Bir şeyi karşılaştırıyor.',
  ],
};

export const REACTION_TEXTS: Record<OwlPersonality, Record<TameAction, string[]>> = {
  aggressive: {
    silent: [
      'Sessizliğini fark etti. Tüyleri biraz indi. Ama gözleri hâlâ keskin.',
      'Hareketsiz durman onu şaşırttı. Beklediği bu değildi.',
      'Sessizliğin onu rahatsız etti. Saldırmak için bahane arıyor.',
      'Durduğun için sinirli. Ama saldırmadı. Henüz.',
      'Sessizliğin bir tuzak mı diye düşünüyor. Temkinli.',
    ],
    distract: [
      'Dikkatini çekmeye çalıştın. Hata. Gözleri daha da daraldı.',
      'Hareketi gördü. Kanatlarını açtı. Saldırı pozisyonu.',
      'Sesini duydu. Başını çevirdi. Öfkeli.',
      'Dikkat çekmen onu kızdırdı. Sabırsızlığı arttı.',
      'Harekete geçtin, o da geçti. Ama saldırmadı — uyardı.',
    ],
    advance: [
      'İlerlediğini gördü. Çığlık attı. Uyarı.',
      'Yaklaştın. O da yaklaştı. Mesafe kapandı. Tehlikeli.',
      'Üzerine gittin. Kanatlarını açtı, gagasını gösterdi.',
      'Cesaretin onu şaşırttı. Bir an duraksadı.',
      'İlerleme hamlesi onu test etti. Geri çekilmedi.',
    ],
  },
  timid: {
    silent: [
      'Sessizliğin onu biraz rahatlattı. Tüyleri indi.',
      'Hareketsiz durman güven verdi. Bir adım yaklaştı.',
      'Sessizliğin içinde bir şey hissetti. Merak mı?',
      'Durduğun için nefes aldı. Kaçmayı düşünmüyor artık.',
      'Sessizliğin onu tuttu. Kaçmak yerine bekledi.',
    ],
    distract: [
      'Hareketi gördü. Zıpladı. Kaçmak üzere.',
      'Sesi duydu. Dondu. Sonra titredi.',
      'Dikkat çekmen onu korkuttu. Geri çekildi.',
      'Harekete geçtin, o geride kaldı. Mesafe açıldı.',
      'Sesini duyunca küçüldü. Görünmez olmaya çalışıyor.',
    ],
    advance: [
      'Yaklaştın. O kaçtı. Ama çok uzağa gitmedin.',
      'İlerleme onu korkuttu. Ama hâlâ orada.',
      'Üzerine gittin. Titredi. Ama kalmayı seçti.',
      'Yaklaşman onu bunalttı. Gözleri yaşlı.',
      'İlerlediğinde dondu. Kaçmak mı, kalmak mı — karar veremedi.',
    ],
  },
  curious: {
    silent: [
      'Sessizliğin onu hayal kırıklığına uğrattı. Daha fazlasını bekliyordu.',
      'Durduğun için kafası karıştı. Sana yaklaştı.',
      'Sessizliğin ilginç geldi. Başını eğdi.',
      'Hareketsizliğin bir bulmaca gibi. Çözmeye çalışıyor.',
      'Sessizliğin içinde bir şey buldu. Seni incelemeye devam ediyor.',
    ],
    distract: [
      'Hareketi gördü. Gözleri parladı. İlgilendirildin.',
      'Sesi duydu. Sana doğru döndü. Meraklı.',
      'Dikkat çekmen işe yaradı. Yaklaştı.',
      'Harekete geçtin, o da geçti — ama saldırmak için değil.',
      'Sesini duyunca başını kaldırdı. Yeni bir şey.',
    ],
    advance: [
      'Yaklaştın. O da yaklaştı. Karşılıklı merak.',
      'İlerleme onu heyecanlandırdı. Kanatlarını açtı.',
      'Üzerine gittin. Geri çekilmedi. Bekledi.',
      'Yaklaşman onu memnun etti. Tüyleri kabardı — ama iyi anlamda.',
      'İlerlediğinde seni daha iyi görmek için başını uzattı.',
    ],
  },
  greedy: {
    silent: [
      'Sessizliğin onu sıktı. Bir şey sunman gerekiyor.',
      'Durduğun için hayal kırıklığı. Ellerini kontrol etti.',
      'Sessizliğin içinde bir hesap yaptı. Sonuç: yetersiz.',
      'Hareketsizliğin onu tatmin etmedi. Beklentisi var.',
      'Sessizliğin bir teklif değil. Daha fazlasını istiyor.',
    ],
    distract: [
      'Hareketi gördü. Bir şey mi var? Yaklaştı.',
      'Sesi duydu. Değerli bir şey mi? Döndü.',
      'Dikkat çekmen işe yaradı — ama yanlış sebepten.',
      'Harekete geçtin, o da geçti. Fırsatçı.',
      'Sesini duyunca gözleri parladı. Bir şey var mı?',
    ],
    advance: [
      'Yaklaştın. O da yaklaştı. Ama seni değil, ellerini izliyor.',
      'İlerleme onu cesaretlendirdi. Talep artıyor.',
      'Üzerine gittin. Geri çekilmedi. Pazarlık pozisyonu.',
      'Yaklaşman onu memnun etti. Ama bedeli var.',
      'İlerlediğinde sana baktı. Gözlerinde bir rakam var.',
    ],
  },
  wise: {
    silent: [
      'Sessizliğin onu etkiledi. Sabırlı olduğunu anladı.',
      'Durduğun için başını eğdi. Saygı mı?',
      'Sessizliğin içinde seni ölçtü. Sonuç henüz yok.',
      'Hareketsizliğin bir mesaj. Aldı.',
      'Sessizliğin doğru hamleydi. Tüyleri indi.',
    ],
    distract: [
      'Hareketi gördü. Bekliyordu zaten. Şaşırmadı.',
      'Sesi duydu. Kaynağını biliyordu. Döndü yavaşça.',
      'Dikkat çekmen onu etkilemedi. Daha fazlasını biliyor.',
      'Harekete geçtin, o izledi. Değerlendiriyor.',
      'Sesini duyunca gözlerini kapattı. Sonra açtı. Anladı.',
    ],
    advance: [
      'Yaklaştın. O kıpırdamadı. Güveniyor mu, test mi ediyor?',
      'İlerleme onu şaşırtmadı. Bekliyordu.',
      'Üzerine gittin. Gözlerini kırpmadı. Hazır.',
      'Yaklaşman onu rahatsız etmedi. Ama izliyor.',
      'İlerlediğinde sana baktı. Derin, sakin, kararlı.',
    ],
  },
};

export const SUCCESS_TEXTS: Record<OwlPersonality, string[]> = {
  aggressive: [
    'Direndi. Ama sen daha güçlüydün. Kabul etti.',
    'Saldırmak üzereydi — durdu. Bir şey değişti.',
    'Gözlerindeki öfke söndü. Yerini başka bir şey aldı.',
    'Pençelerini gevşetti. İlk kez. Bu önemli.',
    'Çığlık atmadı. Sessizce kabul etti. Daha güçlü bir teslim.',
    'Kanatlarını indirdi. Savaş bitti. Sen kazandın.',
    'Gagasını kapattı. Artık tehdit yok. Bağ kuruldu.',
    'Gözleri yumuşadı. Hâlâ keskin — ama artık düşman değil.',
    'Bir adım öne geldi. Kendi isteğiyle. İlk kez.',
    'Tüyleri indi. Vücut dili değişti. Artık seninle.',
  ],
  timid: [
    'Titremeyi bıraktı. Küçük ama büyük bir adım.',
    'Sana doğru geldi. Kendi isteğiyle. Mucize gibi.',
    'Gözlerindeki korku azaldı. Yerini merak aldı.',
    'Pençelerini gevşetti. Artık kaçmıyor.',
    'Küçük bir ses çıkardı. Mutlu mu? Belki.',
    'Başını omzuna yasladı. Güvendi. Sana.',
    'Tüyleri düzeldi. Artık savunma pozisyonu yok.',
    'Gözlerini kapattı. Açtı. Hâlâ orada. Seçti.',
    'Bir adım attı. Sonra durdu. Sonra bir adım daha. Seninle.',
    'Sessizce kabul etti. Sessizce bağlandı.',
  ],
  curious: [
    'Merakı onu getirdi. Şimdi daha yakın.',
    'Seni inceledi, beğendi. Kaldı.',
    'Gözleri parladı. Yeni bir şey buldu — seni.',
    'Başını eğdi. Kabul işareti.',
    'Sana doğru uçtu. Omzuna kondu. Karar verdi.',
    'Tüylerini kabarttı — ama bu sefer mutluluktan.',
    'Bir ses çıkardı. Soru değil artık. Cevap.',
    'Etrafında döndü, sonra durdu. Seninle kalmayı seçti.',
    'Gagasıyla elini dürtükledi. Tanıştık.',
    'Gözlerini kırptı. Yavaşça. Güven.',
  ],
  greedy: [
    'Aldığı şeyden memnun. Anlaşma tamam.',
    'Gözlerindeki hesap kapandı. Tatmin oldu.',
    'Pençelerini gevşetti. Bedel ödendi.',
    'Sana yaklaştı. Artık ortak.',
    'Bir ses çıkardı. Onay gibi.',
    'Tüyleri indi. Pazarlık bitti.',
    'Gözleri yumuşadı. Kazandı mı, kaybetti mi — ikisi de.',
    'Başını eğdi. Anlaşma mühürlendi.',
    'Elini gagasıyla tuttu. Bağ kuruldu.',
    'Sessizce kabul etti. Ama gözleri hâlâ hesaplıyor.',
  ],
  wise: [
    'Beklediği buydu. Sabır. Gösterdin.',
    'Gözlerini kapattı. Açtı. Karar verildi.',
    'Başını eğdi. Derin, kasıtlı. Saygı.',
    'Sana doğru yürüdü. Yavaş, emin adımlarla.',
    'Tüyleri indi. Artık savunma yok. Güven var.',
    'Bir ses çıkardı. Tek. Anlam dolu.',
    'Gözleri sana kilitlendi. Artık ayrılmayacak.',
    'Kanatlarını açtı, kapattı. Kabul ritüeli.',
    'Sessizce yanına geldi. Söze gerek yok.',
    'Seni test etti. Geçtin. Artık seninsin.',
  ],
};

export const FAIL_TEXTS: Record<OwlPersonality, string[]> = {
  aggressive: [
    'Saldırdı. Kaçtın. Mesafe açıldı.',
    'Çığlık attı. Uyarı değil bu sefer — gerçek.',
    'Kanatlarını açtı, sana doğru geldi. Geri çekildin.',
    'Gagasıyla vurdu. Hafif. Ama mesaj net.',
    'Öfkesi arttı. Sabırsızlığın bedelini ödüyorsun.',
    'Tüyleri diken diken. Bir sonraki hamle daha sert olacak.',
    'Gözlerindeki öfke büyüdü. Yanlış hamle.',
    'Saldırı pozisyonuna geçti. Geri adım at.',
    'Çığlığı ormanı doldurdu. Uyarı sona erdi.',
    'Pençelerini gösterdi. Gerçek tehdit.',
  ],
  timid: [
    'Kaçtı. Ama çok uzağa gitmedi.',
    'Titredi, geri çekildi. Mesafe açıldı.',
    'Gözlerindeki korku geri döndü.',
    'Küçüldü. Görünmez olmaya çalışıyor.',
    'Bir ses çıkardı — panik sesi.',
    'Kanatlarını açtı, kaçmaya hazırlandı.',
    'Gözleri yaşlı. Hayal kırıklığı mı, korku mu?',
    'Dalın arkasına geçti. Hâlâ orada ama uzak.',
    'Titremeye başladı. Yanlış hamle.',
    'Sesi kesildi. Dondu. Kötü işaret.',
  ],
  curious: [
    'İlgisi azaldı. Başka bir şeye baktı.',
    'Hayal kırıklığı. Beklediği bu değildi.',
    'Geri çekildi. Merakı söndü.',
    'Başını çevirdi. Artık ilginç değilsin.',
    'Bir ses çıkardı — hayal kırıklığı sesi.',
    'Tüyleri indi. Heyecan geçti.',
    'Gözleri söndü. Yanlış hamle.',
    'Uzaklaştı. Ama tamamen gitmedi.',
    'Kafası karıştı. Beklentisi karşılanmadı.',
    'Sana bakmayı bıraktı. Kötü işaret.',
  ],
  greedy: [
    'Yeterli değildi. Geri çekildi.',
    'Gözlerindeki hayal kırıklığı net.',
    'Teklif reddedildi. Mesafe açıldı.',
    'Başını çevirdi. Daha iyi bir teklif bekliyor.',
    'Bir ses çıkardı — şikayet gibi.',
    'Pençelerini gösterdi. Fiyat arttı.',
    'Gözleri soğudu. Hesap tutmadı.',
    'Uzaklaştı. Ama tamamen gitmedi — fiyat değişirse döner.',
    'Hayal kırıklığı açık. Daha fazlasını istiyordu.',
    'Tüyleri indi. Ama bu sefer kötü anlamda.',
  ],
  wise: [
    'Beklediği bu değildi. Geri çekildi.',
    'Gözlerindeki sakinlik bozuldu. Hayal kırıklığı.',
    'Başını çevirdi. Yanlış hamle yaptın.',
    'Sessizce uzaklaştı. Ama tamamen gitmedi.',
    'Bir ses çıkardı — uyarı gibi.',
    'Gözleri kapandı. Açıldı. Karar değişti.',
    'Tüyleri hafifçe kabardı. Sabırsızlık değil — hayal kırıklığı.',
    'Seni test etti. Geçemedin. Henüz.',
    'Uzaklaştı. Ama izliyor. Hâlâ bir şans var.',
    'Sessizlik ağırlaştı. Yanlış yöne gidiyorsun.',
  ],
};

export const CRITICAL_SUCCESS_TEXTS: Record<OwlPersonality, string[]> = {
  aggressive: [
    'İnanılmaz. Saldırmak üzereydi — durdu. Sana baktı. Seçti.',
    'Hiç kimse bu kadar hızlı güven kazanmamıştı. Efsanevi hamle.',
    'Çığlık atmak yerine sessizce geldi. Mucize.',
  ],
  timid: [
    'Titremeyi bıraktı, sana koştu. Hayatında ilk kez güvendi.',
    'Gözlerindeki korku bir anda sevgiye dönüştü. Nadir.',
    'Küçük adımlarla geldi. Her adım bir zafer.',
  ],
  curious: [
    'Seni inceledi, beğendi, seçti. Hepsi bir anda.',
    'Omzuna kondu. Kimseye yapmamıştı bunu.',
    'Gözleri parladı — ve söndü. Artık sadece sen varsın.',
  ],
  greedy: [
    'Hiçbir şey vermeden kazandın. Bu onu şaşırttı da.',
    'Hesabı kapattı. Bedelsiz. İlk kez.',
    'Gözlerindeki açgözlülük yerini başka bir şeye bıraktı.',
  ],
  wise: [
    'Seni çoktan seçmişti. Sadece onaylamasını bekliyordun.',
    'Tek bir hamleyle her şeyi anladı. Mükemmel.',
    'Gözlerini kapattı. Açtı. "Evet" dedi — sözsüz.',
  ],
};

export const CRITICAL_FAIL_TEXTS: Record<OwlPersonality, string[]> = {
  aggressive: [
    'Saldırdı. Gerçekten. Kaçmak zorunda kaldın.',
    'Öfkesi patladı. Encounter kapandı.',
    'Çığlığı her şeyi bitirdi. Kaçtı.',
  ],
  timid: [
    'Korkusu onu yuttu. Bir anda kayboldu.',
    'Panik. Kaçış. Encounter kapandı.',
    'Gözlerindeki korku son kez parladı — sonra gitti.',
  ],
  curious: [
    'İlgisi tamamen söndü. Dönüp bakmadı.',
    'Hayal kırıklığı onu götürdü. Encounter kapandı.',
    'Merakı bitti. Sen de bittin.',
  ],
  greedy: [
    'Teklif çok düşüktü. Gitti. Dönmeyecek.',
    'Hesap tutmadı. Encounter kapandı.',
    'Açgözlülüğü onu götürdü.',
  ],
  wise: [
    'Seni ölçtü. Yetersiz buldun. Gitti.',
    'Sabırsızlığın her şeyi bitirdi.',
    'Gözlerini kapattı. Açmadı. Gitti.',
  ],
};

export const HINT_TEXTS: Record<OwlPersonality, string[]> = {
  aggressive: [
    '💡 Sessiz yaklaşmak öfkesini yatıştırabilir.',
    '💡 Ani hareketler onu kışkırtır.',
    '💡 Sabırlı ol — saldırganlık sabırsızlığı sever.',
    '💡 Güç gösterisi işe yarayabilir. Ama riskli.',
    '💡 Gözlerini kaçırma. Zayıflık gösterme.',
    '💡 Doğrudan yaklaşım onu test eder.',
    '💡 Çok yavaş da olma — bunu zayıflık sayar.',
    '💡 Bir hamle yanlış giderse geri adım at.',
    '💡 Öfkesi sabırsızlıktan besleniyor.',
    '💡 Cesaret göster ama kontrollü.',
  ],
  timid: [
    '💡 Yavaş, sessiz hareketler güven verir.',
    '💡 Ani sesler onu kaçırır.',
    '💡 Sabır burada en güçlü silah.',
    '💡 Göz temasından kaçın — tehdit gibi görünür.',
    '💡 Küçük adımlar büyük fark yaratır.',
    '💡 Sessizlik en iyi dil.',
    '💡 Acele etme — her adım önemli.',
    '💡 Geri çekilmek bazen ilerlemektir.',
    '💡 Korkusu gerçek. Saygı göster.',
    '💡 Güven inşa etmek zaman alır.',
  ],
  curious: [
    '💡 İlginç bir şey göster — dikkatini çeker.',
    '💡 Merakını besle, sıkma.',
    '💡 Yeni hareketler onu heyecanlandırır.',
    '💡 Monoton olma — ilgisi dağılır.',
    '💡 Sürpriz hamle işe yarayabilir.',
    '💡 Onunla oyna — ciddiye alma.',
    '💡 Merakı en büyük avantajın.',
    '💡 Beklenmedik bir şey yap.',
    '💡 Sessizlik onu sıkar.',
    '💡 Aktif ol, dinamik ol.',
  ],
  greedy: [
    '💡 Bir şey sunmak işe yarayabilir.',
    '💡 Değerli görün — değersiz değil.',
    '💡 Pazarlık pozisyonunda ol.',
    '💡 Ellerini göster — ne var ne yok.',
    '💡 Açgözlülüğünü kullan, ona karşı değil.',
    '💡 Bir şey vaat et — gerçek olmak zorunda değil.',
    '💡 Fiyatı düşürme — değerini koru.',
    '💡 Sabırsız davranma — fiyat artar.',
    '💡 Gözlerini izle — ne istediğini söylüyor.',
    '💡 Anlaşma yap, güven değil.',
  ],
  wise: [
    '💡 Sabır burada her şeyden önemli.',
    '💡 Doğru hamle, doğru zamanda.',
    '💡 Acele etme — her şeyi biliyor.',
    '💡 Sessizlik en güçlü mesaj.',
    '💡 Seni test ediyor. Geç.',
    '💡 Tutarlı ol — değişkenlik onu uzaklaştırır.',
    '💡 Saygı göster — karşılık verir.',
    '💡 Gözlerini kaçırma ama dikme de.',
    '💡 Her hamle kasıtlı olmalı.',
    '💡 Bilgeliğine güven — o da güvenecek.',
  ],
};

export const ENDING_TEXTS: Record<'success_calm' | 'success_emotional' | 'success_dominant' | 'fail_escape' | 'fail_vanish' | 'fail_tension', string[]> = {
  success_calm: [
    'Orman sessizleşti. Sadece ikiniz kaldınız. Ve bu yeterliydi.',
    'Hiçbir şey söylenmedi. Hiçbir şeye gerek yoktu.',
    'Yavaşça omzuna kondu. Sanki hep böyleymiş gibi.',
    'Gözlerini kapattı. Açtı. Artık seninle.',
    'Sessizce yanına geldi. Bağ kuruldu.',
  ],
  success_emotional: [
    'Tüyleri titredi. Gözleri doldu mu? Belki. Ama kaldı.',
    'Küçük bir ses çıkardı. Teşekkür mü? Belki.',
    'Sana doğru geldi, durdu. Sonra bir adım daha attı. Seçti.',
    'Gözlerindeki o şey — korku değildi artık. Güvendi.',
    'Bir an için her şey durdu. Sonra o adım attı. Değişti her şey.',
  ],
  success_dominant: [
    'Direndi. Kaybetti. Ama onurla.',
    'Savaştı. Ama sen daha güçlüydün. Kabul etti.',
    'Çığlık atmak yerine sessizce teslim oldu. Daha güçlü bir kabul.',
    'Gözlerindeki öfke söndü. Yerini saygı aldı.',
    'Kazandın. O da kazandı. Farklı şeyler.',
  ],
  fail_escape: [
    'Bir kanat sesi. Sonra sessizlik. Gitti.',
    'Gözden kayboldu. Orman onu yuttu.',
    'Son bir bakış attı. Sonra uçtu. Dönmeyecek.',
    'Rüzgar esti. O gitti. Sadece tüyleri kaldı.',
    'Bir an için durdu. Sonra kararını verdi. Gitti.',
  ],
  fail_vanish: [
    'Fark etmeden kayboldu. Hiç orada olmamış gibi.',
    'Gözlerini kırptın. Yoktu artık.',
    'Sessizce gitti. Ses bile çıkarmadı.',
    'Orman onu aldı. Geri vermeyecek.',
    'Bir gölge gibi kayboldu.',
  ],
  fail_tension: [
    'Gerilim patladı. Her şey bitti.',
    'Son hamle yanlıştı. Telafi edilemez.',
    'Öfkesi onu götürdü. Seni de götürebilirdi.',
    'Bir çığlık. Sonra sessizlik. Encounter kapandı.',
    'Sabır tükendi — ikisi için de.',
  ],
};
